name: Tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
    - main
    tags:
    - "v*"

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: false

jobs:
  windows-build:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-2022, windows-2025 ]
        compiler: [ { c: "clang-cl", cxx: "clang-cl" } ]
    name: Windows - ${{ matrix.os }} - ${{ matrix.compiler.cxx }}
    runs-on: ${{ matrix.os }}

    env:
      triplet: x64-windows

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Configure VS Toolchain
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install dependencies
      run: vcpkg install yyjson gtest --triplet ${{ env.triplet }}

    - name: Build and test
      run: |
        rm -rf "${{ github.workspace }}\build"
        cmake -B "${{ github.workspace }}\build" -DCMAKE_TOOLCHAIN_FILE="$VCPKG_INSTALLATION_ROOT\\scripts\\buildsystems\\vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=${{ env.triplet }} -DCMAKE_CXX_COMPILER=${{ matrix.compiler.cxx }} -G "Ninja Multi-Config"
        # cmake --build "${{ github.workspace }}\build" --config Debug --clean-first
        # ctest --test-dir "${{ github.workspace }}\build" -C Debug
        cmake --build "${{ github.workspace }}\build" --config Release --clean-first
        ctest --test-dir "${{ github.workspace }}\build" -C Release
      shell: bash

  ubuntu-build:
    strategy:
      fail-fast: false
      matrix:
        compiler:
        - { name: "GCC 13", os: "ubuntu-24.04", install: "apt", c: "gcc-13", cxx: "g++-13", packages: "gcc-13 g++-13" }
        - { name: "GCC 14", os: "ubuntu-24.04", install: "apt", c: "gcc-14", cxx: "g++-14", packages: "gcc-14 g++-14" }
        - { name: "GCC 15", os: "ubuntu-26.04", install: "apt", c: "gcc-15", cxx: "g++-15", packages: "gcc-15 g++-15" }
        - { name: "GCC 16", os: "ubuntu-26.04", install: "apt", c: "gcc-16", cxx: "g++-16", packages: "gcc-16 g++-16" }
        - { name: "LLVM 17", os: "ubuntu-24.04", install: "brew", c: "$(brew --prefix llvm@17)/bin/clang", cxx: "$(brew --prefix llvm@17)/bin/clang++", brewpkg: "llvm@17" }
        - { name: "LLVM 18", os: "ubuntu-24.04", install: "brew", c: "$(brew --prefix llvm@18)/bin/clang", cxx: "$(brew --prefix llvm@18)/bin/clang++", brewpkg: "llvm@18" }
        - { name: "LLVM 19", os: "ubuntu-24.04", install: "brew", c: "$(brew --prefix llvm@19)/bin/clang", cxx: "$(brew --prefix llvm@19)/bin/clang++", brewpkg: "llvm@19" }
        - { name: "LLVM 20", os: "ubuntu-24.04", install: "brew", c: "$(brew --prefix llvm@20)/bin/clang", cxx: "$(brew --prefix llvm@20)/bin/clang++", brewpkg: "llvm@20" }
        - { name: "LLVM 21", os: "ubuntu-24.04", install: "brew", c: "$(brew --prefix llvm@21)/bin/clang", cxx: "$(brew --prefix llvm@21)/bin/clang++", brewpkg: "llvm@21" }
        - { name: "LLVM 22", os: "ubuntu-24.04", install: "brew", c: "$(brew --prefix llvm@22)/bin/clang", cxx: "$(brew --prefix llvm@22)/bin/clang++", brewpkg: "llvm@22" }
    name: Ubuntu - ${{ matrix.compiler.name }}
    runs-on: ${{ matrix.compiler.os }}

    env:
      triplet: x64-linux

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install compilers
      run: |
        if [[ "${{ matrix.compiler.install }}" == "brew" ]]; then
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install ninja ${{ matrix.compiler.brewpkg }}
        else
          sudo apt-get update
          sudo apt-get install -y ninja-build ${{ matrix.compiler.packages }}
        fi

    - name: Install dependencies
      run: |
        if [[ "${{ matrix.compiler.install }}" == "brew" ]]; then
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        fi
        CC=${{ matrix.compiler.c }} CXX=${{ matrix.compiler.cxx }} vcpkg install yyjson gtest --triplet ${{ env.triplet }}

    - name: Build and test
      run: |
        if [[ "${{ matrix.compiler.install }}" == "brew" ]]; then
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        fi
        rm -rf ${{ github.workspace }}/build
        cmake -B ${{ github.workspace }}/build -DCMAKE_TOOLCHAIN_FILE=$VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=${{ env.triplet }} -DCMAKE_C_COMPILER=${{ matrix.compiler.c }} -DCMAKE_CXX_COMPILER=${{ matrix.compiler.cxx }} -G "Ninja Multi-Config"
        cmake --build ${{ github.workspace }}/build --config Debug --clean-first
        ctest --test-dir ${{ github.workspace }}/build -C Debug
        cmake --build ${{ github.workspace }}/build --config Release --clean-first
        ctest --test-dir ${{ github.workspace }}/build -C Release

  macos-build:
    strategy:
      fail-fast: false
      matrix:
        compiler:
        - { name: "GCC 15", c: "gcc-15", cxx: "g++-15", brewpkg: "gcc@15" }
        - { name: "GCC 16", c: "gcc-16", cxx: "g++-16", brewpkg: "gcc@16" }
        - { name: "Clang 19", c: "$(brew --prefix llvm@19)/bin/clang", cxx: "$(brew --prefix llvm@19)/bin/clang++", brewpkg: "llvm@19" }
        - { name: "Clang 20", c: "$(brew --prefix llvm@20)/bin/clang", cxx: "$(brew --prefix llvm@20)/bin/clang++", brewpkg: "llvm@20" }
        - { name: "Clang 21", c: "$(brew --prefix llvm@21)/bin/clang", cxx: "$(brew --prefix llvm@21)/bin/clang++", brewpkg: "llvm@21" }
        - { name: "Clang 22", c: "$(brew --prefix llvm@22)/bin/clang", cxx: "$(brew --prefix llvm@22)/bin/clang++", brewpkg: "llvm@22" }
    name: MacOS - ${{ matrix.compiler.name }}
    runs-on: macos-latest

    env:
      triplet: arm64-osx

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install compilers
      run: brew install ninja ${{ matrix.compiler.brewpkg }}

    - name: Install dependencies
      run: |
        git clone --depth 1 https://github.com/microsoft/vcpkg.git external/vcpkg
        ./external/vcpkg/bootstrap-vcpkg.sh
        CC=${{ matrix.compiler.c }} CXX=${{ matrix.compiler.cxx }} ./external/vcpkg/vcpkg install yyjson gtest --triplet ${{ env.triplet }}

    - name: Build and test
      run: |
        rm -rf ${{ github.workspace }}/build
        cmake -B ${{ github.workspace }}/build -DCMAKE_TOOLCHAIN_FILE=./external/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=${{ env.triplet }} -DCMAKE_C_COMPILER=${{ matrix.compiler.c }} -DCMAKE_CXX_COMPILER=${{ matrix.compiler.cxx }} -G "Ninja Multi-Config"
        cmake --build ${{ github.workspace }}/build --config Debug --clean-first
        ctest --test-dir ${{ github.workspace }}/build -C Debug
        cmake --build ${{ github.workspace }}/build --config Release --clean-first
        ctest --test-dir ${{ github.workspace }}/build -C Release
